### ISSUE TITLE
Error while plotting Smudgeplot 

### ISSUE THREAD

**Issue by ktallen45** [KamilSJaron/smudgeplot#150] opened 2024-06-07 20:06 UTC
Good afternoon, 

I am running smudgeplot on a target capture dataset for a species of frog that we believe to be polyploid but dont know the ploidy level. Everything runs normally until the end when I try to create the smudge plot and I get this error: 

[ktapondjou@login7 Astylosternus_ranoides_TKM_499]$ smudgeplot.py plot kmcdb_L"$L"_U"$U"_coverages.tsv
Running smudgeplot v0.2.3dev
Task: plot
Calling: smudgeplot_plot.R -i "kmcdb_L150_U650_coverages.tsv" -o "smudgeplot" -k 21
######################
######################
Error in if (abs(peak_frame_6$cov[1] - peak_frame_5$cov[1]) <= 5 & peak_frame_6$height[1] >  : 
  missing value where TRUE/FALSE needed
Calls: estimate_1n_coverage_1d_subsets
Execution halted
Done!

Im attaching the rest of the script below so you can see how all of the values look. What does this error mean? is it something resolvable or an issue with my dataset (coverage maybe?)? 

Thank you! 

Katie 
[smudgeplot_script_ranoides.docx](https://github.com/user-attachments/files/15744399/smudgeplot_script_ranoides.docx)

**Comment by KamilSJaron** [comment] 2024-06-10 22:02
Hi Katie, I suspect the problem is the target capture, smudgeplot is not really designed for that. See FAQ:

https://github.com/KamilSJaron/smudgeplot/wiki/FAQ#9-can-i-use-smudgeplot-on-reduced-representation-sequencing

There are some more details about what exactly is expected on the input here: https://github.com/KamilSJaron/smudgeplot/wiki/everything-about-input-data

You can try at least plot the k-mer histogram (for example by running genomescope), if you won't see any peaks, I am afraid there is no point in attempting running smudgeplot.

**Comment by KamilSJaron** [comment] 2024-06-10 22:04
I will close it for now, but feel free to reopen if necessary.

**Closed by KamilSJaron** 2024-06-10 22:04 UTC

**Comment by ktallen45** [comment] 2024-06-10 22:09
Hi Kamil,

Thank you so much for your response!! I was afraid that was going to be the problem. I just ran genoscope as your suggested and there were no peaks.

Thanks again,

Katie

On Jun 10, 2024, at 6:03 PM, Kamil S. Jaron ***@***.***> wrote:

[External Email]


Hi Katie, I suspect the problem is the target capture, smudgeplot is not really designed for that. See FAQ:

https://github.com/KamilSJaron/smudgeplot/wiki/FAQ#9-can-i-use-smudgeplot-on-reduced-representation-sequencing

There are some more details about what exactly is expected on the input here: https://github.com/KamilSJaron/smudgeplot/wiki/everything-about-input-data

You can try at least plot the k-mer histogram (for example by running genomescope), if you won't see any peaks, I am afraid there is no point in attempting running smudgeplot.
