### ISSUE TITLE
PloidyPlot: Something went wrong with command:

### ISSUE THREAD

**Issue by Malabady** [KamilSJaron/smudgeplot#166] opened 2024-10-21 14:30 UTC
Hi, 
I am getting the following error:

``
PloidyPlot: Something went wrong with command:
    Logex -T4 '.trim=A[12-]' Outdata/FastK_table
``

my command is: ``PloidyPlot -e12 -k -v -T4 -oOutdata/kmerpairs Outdata/FastK_table``

Any suggestions? 

Many thanks,

**Comment by Malabady** [comment] 2024-10-23 19:11
No, it doesn’t say that. In fact, I checked the Logex command and it is installed already.

From: Kamil S. Jaron ***@***.***>
Date: Wednesday, October 23, 2024 at 3:07 PM
To: KamilSJaron/smudgeplot ***@***.***>
Cc: Magdy S Alabady ***@***.***>, Author ***@***.***>
Subject: Re: [KamilSJaron/smudgeplot] PloidyPlot: Something went wrong with command: (Issue #166)
[EXTERNAL SENDER - PROCEED CAUTIOUSLY]

Does it also say sh: Logex: command not found? It looks like an incomplete installation (missing some parts of FastK)

**Comment by yaradua** [comment] 2024-10-23 19:24
The problem is with the installation of the fastK. you need to direct the installation to the bin directory and all the programs will be installed

**Comment by KamilSJaron** [comment] 2024-10-24 07:04
AH, thanks @yaradua.

@Malabady Can you double check you have the installation available in the environment? If that's not going to help, can you past the whole error?

**Comment by Malabady** [comment] 2024-10-24 11:11
Thanks, @yaradua and @KamilSJaron 

the smudgeplot tool is installed as a module on our computer cluster with the FastK tool. I load the module as follows:

``
ml Smudgeplot/0.3.0dev-foss-2022a-Sploidyplot-branch
``
after loading the module, all commands are in the environment path. I checked "FastK", "PloidyPlot", and "Logex" and they all are in the path.  for instance, here is the Logex command:

```
07:04:45    $ Logex
Usage: Logex  [-T<int(4)>] [-[hH][<int(1)>:]<int>]
                <output:name=expr> ... <source_root>[.ktab] ...
      -T: Use -T threads.
      -h: Generate histograms.
      -H: Generate histograms only, no tables.
```

Then, I ran the following commands:

```
FastK -v -t24 -k31 -M300 -T4 Indata/*.fasta.gz -NOutdata/FastK_table

PloidyPlot -e12 -k -v -T4 -oOutdata/kmerpairs Outdata/FastK_table
```

here is the complete stdout and stderr 

```
Using 3 threads to read 3 fasta files some or all of which are compressed

Determining minimizer scheme & partition for FastK_table
  Estimate 339.653G 31-mers
  Dividing data into 12 blocks
  Using 5-minimizers with 1024 core prefixes

Phase 1: Partitioning K-mers into 36 Super-mer Files

  There are 1,057,160,093 reads totalling 463,388,761,914 bps

     Part:           31-mer      super-mers  ave. length
        0:   35,357,798,942   2,367,911,641         14.9
        1:   35,154,763,597   2,669,851,643         13.2
        2:   38,938,442,209   2,416,621,617         16.1
        3:   35,376,383,886   3,379,431,155         10.5
        4:   35,231,744,001   2,654,632,960         13.3
        5:   36,043,428,326   3,595,457,451         10.0
        6:   37,334,894,602   3,068,535,603         12.2
        7:   35,415,697,671   2,555,267,339         13.9
        8:   35,384,503,758   3,177,470,552         11.1
        9:   36,336,968,042   3,168,617,920         11.5
       10:   35,711,734,433   2,839,981,671         12.6
       11:   34,892,586,685   2,763,644,563         12.6
      Sum:  431,178,946,152  34,657,424,115         12.4

      Range 34,892,586,685 - 38,938,442,209 (10.96%)

  Resources for phase:  93:11.448u  2:04.378s  64:24.419w  147.9%

Phase 2: Sorting & Counting K-mers in 12 blocks

      Part:    wgt'd k-mers  savings
         0:   5,003,788,576      7.1
         1:   4,997,654,629      7.0
         2:   6,927,090,730      5.6
         3:   4,925,254,790      7.2
         4:   4,922,413,475      7.2
         5:   4,924,727,592      7.3
         6:   4,968,430,478      7.5
         7:   4,744,539,388      7.5
         8:   4,807,449,310      7.4
         9:   5,323,877,363      6.8
        10:   4,927,074,619      7.2
        11:   4,885,068,823      7.1
       All:  61,357,369,773      7.0

  Resources for phase:  116:13.454u  2:05.208s  37:55.233w  312.0%

Phase 3 (-t option): Merging K-mer Table Parts

  There are 1,986,881,634 31-mers that occur 24-or-more times

  The table occupies 14.04 GB

  Resources for phase:  1:43.007u  14.257s  41.225w  284.4%

Total Resources:  211:07.910u  4:23.845s  103:00.878w  209.2%  109MB

  The input table is untrimmed and not symmetric

  Trimming k-mers in table with count < 12
PloidyPlot: Something went wrong with command:
    Logex -T4 '.trim=A[12-]' Outdata/FastK_table

```

**Comment by Malabady** [comment] 2024-10-26 14:18
Hi All, 

I want to report that our team were able to find the problem. the values for the parameters "T" and "t" in the `FastK` command were flipped:

```
FastK -v -t24 -k31 -M300 -T4 Indata/*.fasta.gz -NOutdata/FastK_table
```

once fixed as follows, everything worked just fine:

``
FastK -v -t4 -k31 -M300 -T24 Indata/*.fasta.gz -NOutdata/FastK_table
``
thank you for your time,

**Comment by KamilSJaron** [comment] 2024-10-29 08:58
AAAaaaaaaaaaaa,  that's something I should have spotted!

Thank you @Malabady for reporting this back, it will be very useful to know when others will run into the same issue. (The `-T` and `-t` parameters of FastK have very unfortunate names!!!)

**Closed** 2024-10-29 08:58 UTC
